repos:
  - repo: https://gitlab.com/pycqa/flake8
    rev: "3.7.9"
    hooks:
      - id: flake8
        additional_dependencies: ["flake8-bugbear==19.8.0"]
        args:
          - --config=.flake8
  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black
        language_version: python3
